image&nbsp;&nbsp;&nbsp;	name&nbsp;	pass&nbsp;&nbsp;&nbsp;	fail&nbsp;&nbsp;&nbsp;	errors&nbsp;&nbsp;&nbsp;	skipped&nbsp;&nbsp;&nbsp;	avg time&nbsp;	fail msg&nbsp;
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.TestProcedureRollbackAIOOB#testArrayIndexOutOfBounds	60	0	 0	0	13.65	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.replication.TestReplicationEndpoint#testWALEntryFilterAddValidation	100	0	 0	0	2.68	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.TestProcedureRecovery#testStateMachineRollbackRecovery	100	0	 0	0	4.40	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.TestChildProcedures#testChildRollbackLoad	100	0	 0	0	1.56	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestStripeStoreEngine#testCompactionContextForceSelect	100	0	 0	0	.46	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestSyncTimeRangeTracker#testAlwaysDecrementingSetsMaximum	201	0	 0	0	.05	
<img src="/images/failed.png" height="14" width="14">	org.apache.hadoop.hbase.client.TestSeparateClientZKCluster#testMasterSwitch	33	7	 32	0	104.92	sleep interrupted<br/><br/>java.lang.InterruptedException: sleep interrupted<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.sleep(Native Method)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.TestSeparateClientZKCluster.testMasterSwitch(TestSeparateClientZKCluster.java:133)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>&nbsp; &nbsp;at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)<br/>&nbsp; &nbsp;at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)<br/>&nbsp; &nbsp;at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.TestProcedureRecovery#testMultiStepProcRecovery	100	0	 0	0	1.09	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestSyncTimeRangeTracker#testExtreme	201	0	 0	0	.05	
<img src="/images/failed.png" height="14" width="14">	org.apache.hadoop.hbase.client.TestSeparateClientZKCluster#testMetaMoveDuringClientZkClusterRestart	8	3	 51	0	9.32	Failed after attempts=3, exceptions:<br/>2020-02-03T22:18:16.593Z, org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:<br/>2020-02-03T22:18:10.062Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:18:13.307Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:18:16.588Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/><br/>2020-02-03T22:18:25.771Z, org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:<br/>2020-02-03T22:18:19.847Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:18:22.671Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:18:25.770Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/><br/>2020-02-03T22:18:35.526Z, org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:<br/>2020-02-03T22:18:29.017Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:18:33.002Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:18:35.525Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/><br/><br/><br/>org.apache.hadoop.hbase.client.RetriesExhaustedException: <br/>Failed after attempts=3, exceptions:<br/>2020-02-03T22:18:16.593Z, org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:<br/>2020-02-03T22:18:10.062Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:18:13.307Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:18:16.588Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/><br/>2020-02-03T22:18:25.771Z, org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:<br/>2020-02-03T22:18:19.847Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:18:22.671Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:18:25.770Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/><br/>2020-02-03T22:18:35.526Z, org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:<br/>2020-02-03T22:18:29.017Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:18:33.002Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:18:35.525Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/><br/><br/>&nbsp; &nbsp;at java.base/java.lang.Thread.getStackTrace(Thread.java:1606)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.setStackTrace(FutureUtils.java:130)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.rethrow(FutureUtils.java:145)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.get(FutureUtils.java:168)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.TableOverAsyncTable.get(TableOverAsyncTable.java:180)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.TestSeparateClientZKCluster.testMetaMoveDuringClientZkClusterRestart(TestSeparateClientZKCluster.java:228)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>&nbsp; &nbsp;at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)<br/>&nbsp; &nbsp;at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)<br/>&nbsp; &nbsp;at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>&nbsp; &nbsp;at --------Future.get--------(Unknown Source)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRpcRetryingCaller.completeExceptionally(AsyncRpcRetryingCaller.java:111)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRpcRetryingCaller.onError(AsyncRpcRetryingCaller.java:181)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncSingleRequestRpcRetryingCaller.lambda$doCall$7(AsyncSingleRequestRpcRetryingCaller.java:110)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRegionLocator.lambda$getRegionLocation$3(AsyncRegionLocator.java:110)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncNonMetaRegionLocator.complete(AsyncNonMetaRegionLocator.java:304)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncNonMetaRegionLocator.access$500(AsyncNonMetaRegionLocator.java:71)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncNonMetaRegionLocator$1.onError(AsyncNonMetaRegionLocator.java:447)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncClientScanner.lambda$openScanner$2(AsyncClientScanner.java:209)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRpcRetryingCaller.completeExceptionally(AsyncRpcRetryingCaller.java:111)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRpcRetryingCaller.onError(AsyncRpcRetryingCaller.java:181)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncSingleRequestRpcRetryingCaller.lambda$doCall$7(AsyncSingleRequestRpcRetryingCaller.java:110)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRegionLocator.lambda$getRegionLocation$3(AsyncRegionLocator.java:110)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.ConnectionUtils.lambda$getOrFetch$6(ConnectionUtils.java:558)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.ZKAsyncRegistry.lambda$getMetaRegionLocation$5(ZKAsyncRegistry.java:202)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient$ZKTask$1.exec(ReadOnlyZKClient.java:198)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient.run(ReadOnlyZKClient.java:342)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>Caused by: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:<br/>2020-02-03T22:18:29.017Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:18:33.002Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:18:35.525Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/><br/>&nbsp; &nbsp;... 29 more<br/>Caused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>&nbsp; &nbsp;at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)<br/>&nbsp; &nbsp;at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)<br/>&nbsp; &nbsp;... 3 more<br/>
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestSyncTimeRangeTracker#testTimeRangeInitialized	201	0	 0	0	.05	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestSyncTimeRangeTracker#testLegacySerialization	201	0	 0	0	.05	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.TestProcedureRecovery#testMultiStepRollbackRecovery	100	0	 0	0	4.57	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.TestChildProcedures#testChildLoad	100	0	 0	0	.31	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.TestChildProcedures#testChildLoadWithSteppedRestart	100	0	 0	0	1.11	
<img src="/images/failed.png" height="14" width="14">	org.apache.hadoop.hbase.replication.TestReplicationEndpoint#testWALEntryFilterUpdateValidation	98	0	 2	0	4.39	Failed after attempts=15, exceptions:<br/>2020-02-03T21:50:38.950Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:39.058Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:39.268Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:39.577Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:40.090Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:41.111Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:43.131Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:47.154Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:57.203Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:51:07.249Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:51:18.020Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:51:28.115Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:51:48.240Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:52:08.296Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:52:28.431Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/><br/><br/>org.apache.hadoop.hbase.client.RetriesExhaustedException: <br/>Failed after attempts=15, exceptions:<br/>2020-02-03T21:50:38.950Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:39.058Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:39.268Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:39.577Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:40.090Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:41.111Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:43.131Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:47.154Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:57.203Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:51:07.249Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:51:18.020Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:51:28.115Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:51:48.240Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:52:08.296Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:52:28.431Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/><br/>&nbsp; &nbsp;at java.base/java.lang.Thread.getStackTrace(Thread.java:1606)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.setStackTrace(FutureUtils.java:130)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.rethrow(FutureUtils.java:145)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.get(FutureUtils.java:168)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AdminOverAsyncAdmin.rollWALWriter(AdminOverAsyncAdmin.java:574)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.replication.TestReplicationEndpoint.setup(TestReplicationEndpoint.java:106)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>&nbsp; &nbsp;at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)<br/>&nbsp; &nbsp;at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>&nbsp; &nbsp;at --------Future.get--------(Unknown Source)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRpcRetryingCaller.completeExceptionally(AsyncRpcRetryingCaller.java:111)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRpcRetryingCaller.onError(AsyncRpcRetryingCaller.java:181)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncAdminRequestRetryingCaller.lambda$doCall$4(AsyncAdminRequestRetryingCaller.java:68)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.RawAsyncHBaseAdmin$2.run(RawAsyncHBaseAdmin.java:431)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.com.google.protobuf.RpcUtil$1.run(RpcUtil.java:79)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.com.google.protobuf.RpcUtil$1.run(RpcUtil.java:70)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:380)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:91)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:409)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:405)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.BufferCallBeforeInitHandler.userEventTriggered(BufferCallBeforeInitHandler.java:92)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:344)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:330)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:322)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.DefaultChannelPipeline$HeadContext.userEventTriggered(DefaultChannelPipeline.java:1428)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:344)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:330)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.DefaultChannelPipeline.fireUserEventTriggered(DefaultChannelPipeline.java:913)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcConnection.failInit(NettyRpcConnection.java:179)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcConnection.access$500(NettyRpcConnection.java:71)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcConnection$3.operationComplete(NettyRpcConnection.java:267)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcConnection$3.operationComplete(NettyRpcConnection.java:261)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>Caused by: java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:177)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:378)<br/>&nbsp; &nbsp;... 34 more<br/>Caused by: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>Caused by: java.net.ConnectException: Connection refused<br/>&nbsp; &nbsp;at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)<br/>&nbsp; &nbsp;at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.util.TestDelayedUtil#testDelayedContainerEquals	100	0	 0	0	.06	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.TestProcedureMetrics#testMetricForFailedYiledProcedure	100	0	 0	0	1.57	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.TestProcedureMetrics#testMetricsForFailedProcedure	100	0	 0	0	.30	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.TestProcedureRecovery#testStateMachineRecovery	100	0	 0	0	1.34	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.TestChildProcedures#testChildLoadWithRestartAfterChildSuccess	100	0	 0	0	1.11	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestSyncTimeRangeTracker#testArriveAtRightAnswer	201	0	 0	0	.14	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.TestProcedureRecovery#testSingleStepProcRecovery	100	0	 0	0	.58	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestSyncTimeRangeTracker#testSerialization	201	0	 0	0	.12	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.TestChildProcedures#testChildRollbackLoadWithSteppedRestart	100	0	 0	0	.82	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestSyncTimeRangeTracker#testConcurrentIncludeTimestampCorrectness	201	0	 0	0	8.53	
<img src="/images/failed.png" height="14" width="14">	org.apache.hadoop.hbase.client.TestSeparateClientZKCluster#testMetaRegionMove	25	0	 47	0	4.03	testMetaRegionMove<br/><br/>org.apache.hadoop.hbase.TableNotFoundException: testMetaRegionMove<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.getStackTrace(Thread.java:1606)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.setStackTrace(FutureUtils.java:130)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.rethrow(FutureUtils.java:145)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.get(FutureUtils.java:168)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.TableOverAsyncTable.put(TableOverAsyncTable.java:205)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.TestSeparateClientZKCluster.testMetaRegionMove(TestSeparateClientZKCluster.java:157)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>&nbsp; &nbsp;at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)<br/>&nbsp; &nbsp;at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)<br/>&nbsp; &nbsp;at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>&nbsp; &nbsp;at --------Future.get--------(Unknown Source)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncNonMetaRegionLocator$1.onComplete(AsyncNonMetaRegionLocator.java:453)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncClientScanner.lambda$startScan$1(AsyncClientScanner.java:183)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.addListener(FutureUtils.java:61)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncClientScanner.startScan(AsyncClientScanner.java:166)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncClientScanner.lambda$openScanner$2(AsyncClientScanner.java:212)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncSingleRequestRpcRetryingCaller.lambda$call$4(AsyncSingleRequestRpcRetryingCaller.java:90)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncClientScanner.lambda$callOpenScanner$0(AsyncClientScanner.java:157)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.com.google.protobuf.RpcUtil$1.run(RpcUtil.java:79)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.com.google.protobuf.RpcUtil$1.run(RpcUtil.java:70)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:383)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:91)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:409)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:405)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.Call.setResponse(Call.java:149)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcDuplexHandler.readResponse(NettyRpcDuplexHandler.java:184)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcDuplexHandler.channelRead(NettyRpcDuplexHandler.java:192)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:316)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>
<img src="/images/failed.png" height="14" width="14">	org.apache.hadoop.hbase.replication.TestReplicationEndpoint#testInterClusterReplication	65	33	 2	0	25.32	Waiting timed out after [30,000] msec Failed to replicate all edits, expected = 2500 replicated = 2499<br/><br/>java.lang.AssertionError: Waiting timed out after [30,000] msec Failed to replicate all edits, expected = 2500 replicated = 2499<br/>&nbsp; &nbsp;at org.junit.Assert.fail(Assert.java:89)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.Waiter.waitFor(Waiter.java:203)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.Waiter.waitFor(Waiter.java:137)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.replication.TestReplicationEndpoint.testInterClusterReplication(TestReplicationEndpoint.java:235)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>&nbsp; &nbsp;at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)<br/>&nbsp; &nbsp;at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.TestProcedureMetrics#testMetricForYieldProcedure	100	0	 0	0	.32	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.TestProcedureEvents#testTimeoutEventProcedureDoubleExecution	100	0	 0	0	5.88	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.TestProcedureMetrics#testMetricForProcedureWithChildren	100	0	 0	0	.32	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestRegionReplicasWithRestartScenarios#testRegionReplicasCreated	100	0	 0	0	12.45	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.TestLockAndQueue#testHasLockAccess	100	0	 0	0	.27	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.TestProcedureEvents#testTimeoutEventProcedure	100	0	 0	0	3.30	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.replication.TestReplicationEndpoint#testCustomReplicationEndpoint	100	0	 0	0	6.57	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestSyncTimeRangeTracker#testTimeRangeTrackerNullIsSameAsTimeRangeNull	201	0	 0	0	.05	
<img src="/images/failed.png" height="14" width="14">	org.apache.hadoop.hbase.client.TestSeparateClientZKCluster#testBasicOperation	16	0	 46	0	2.39	Failed after attempts=3, exceptions:<br/>2020-02-03T22:18:45.931Z, org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:<br/>2020-02-03T22:18:39.191Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:18:43.047Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:18:45.929Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/><br/>2020-02-03T22:18:56.731Z, org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:<br/>2020-02-03T22:18:49.795Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:18:52.732Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:18:56.729Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/><br/>2020-02-03T22:19:06.426Z, org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:<br/>2020-02-03T22:18:59.729Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:19:03.157Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:19:06.425Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/><br/><br/><br/>org.apache.hadoop.hbase.client.RetriesExhaustedException: <br/>Failed after attempts=3, exceptions:<br/>2020-02-03T22:18:45.931Z, org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:<br/>2020-02-03T22:18:39.191Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:18:43.047Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:18:45.929Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/><br/>2020-02-03T22:18:56.731Z, org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:<br/>2020-02-03T22:18:49.795Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:18:52.732Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:18:56.729Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/><br/>2020-02-03T22:19:06.426Z, org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:<br/>2020-02-03T22:18:59.729Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:19:03.157Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:19:06.425Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/><br/><br/>&nbsp; &nbsp;at java.base/java.lang.Thread.getStackTrace(Thread.java:1606)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.setStackTrace(FutureUtils.java:130)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.rethrow(FutureUtils.java:145)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.get(FutureUtils.java:168)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.TableOverAsyncTable.put(TableOverAsyncTable.java:205)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.TestSeparateClientZKCluster.testBasicOperation(TestSeparateClientZKCluster.java:111)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>&nbsp; &nbsp;at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)<br/>&nbsp; &nbsp;at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)<br/>&nbsp; &nbsp;at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>&nbsp; &nbsp;at --------Future.get--------(Unknown Source)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRpcRetryingCaller.completeExceptionally(AsyncRpcRetryingCaller.java:111)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRpcRetryingCaller.onError(AsyncRpcRetryingCaller.java:181)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncSingleRequestRpcRetryingCaller.lambda$doCall$7(AsyncSingleRequestRpcRetryingCaller.java:110)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRegionLocator.lambda$getRegionLocation$3(AsyncRegionLocator.java:110)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncNonMetaRegionLocator.complete(AsyncNonMetaRegionLocator.java:304)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncNonMetaRegionLocator.access$500(AsyncNonMetaRegionLocator.java:71)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncNonMetaRegionLocator$1.onError(AsyncNonMetaRegionLocator.java:447)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncClientScanner.lambda$openScanner$2(AsyncClientScanner.java:209)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRpcRetryingCaller.completeExceptionally(AsyncRpcRetryingCaller.java:111)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRpcRetryingCaller.onError(AsyncRpcRetryingCaller.java:181)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncSingleRequestRpcRetryingCaller.lambda$doCall$7(AsyncSingleRequestRpcRetryingCaller.java:110)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRegionLocator.lambda$getRegionLocation$3(AsyncRegionLocator.java:110)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.ConnectionUtils.lambda$getOrFetch$6(ConnectionUtils.java:558)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.ZKAsyncRegistry.lambda$getMetaRegionLocation$5(ZKAsyncRegistry.java:202)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient$ZKTask$1.exec(ReadOnlyZKClient.java:198)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient.run(ReadOnlyZKClient.java:342)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>Caused by: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=3, exceptions:<br/>2020-02-03T22:18:59.729Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:19:03.157Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>2020-02-03T22:19:06.425Z, org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/><br/>&nbsp; &nbsp;... 29 more<br/>Caused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase<br/>&nbsp; &nbsp;at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)<br/>&nbsp; &nbsp;at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)<br/>&nbsp; &nbsp;... 3 more<br/>
<img src="/images/failed.png" height="14" width="14">	org.apache.hadoop.hbase.replication.TestReplicationEndpoint#testMetricsSourceBaseSourcePassthrough	98	0	 2	0	6.08	Failed after attempts=15, exceptions:<br/>2020-02-03T21:45:01.613Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:01.718Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:01.927Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:02.238Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:02.748Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:04.058Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:06.079Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:10.119Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:20.216Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:30.312Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:40.380Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:50.422Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:46:10.495Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:46:30.510Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:46:50.713Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/><br/><br/>org.apache.hadoop.hbase.client.RetriesExhaustedException: <br/>Failed after attempts=15, exceptions:<br/>2020-02-03T21:45:01.613Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:01.718Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:01.927Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:02.238Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:02.748Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:04.058Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:06.079Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:10.119Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:20.216Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:30.312Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:40.380Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:45:50.422Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:46:10.495Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:46:30.510Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:46:50.713Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/><br/>&nbsp; &nbsp;at java.base/java.lang.Thread.getStackTrace(Thread.java:1606)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.setStackTrace(FutureUtils.java:130)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.rethrow(FutureUtils.java:145)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.get(FutureUtils.java:168)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AdminOverAsyncAdmin.rollWALWriter(AdminOverAsyncAdmin.java:574)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.replication.TestReplicationEndpoint.setup(TestReplicationEndpoint.java:106)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>&nbsp; &nbsp;at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)<br/>&nbsp; &nbsp;at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>&nbsp; &nbsp;at --------Future.get--------(Unknown Source)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRpcRetryingCaller.completeExceptionally(AsyncRpcRetryingCaller.java:111)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRpcRetryingCaller.onError(AsyncRpcRetryingCaller.java:181)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncAdminRequestRetryingCaller.lambda$doCall$4(AsyncAdminRequestRetryingCaller.java:68)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.RawAsyncHBaseAdmin$2.run(RawAsyncHBaseAdmin.java:431)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.com.google.protobuf.RpcUtil$1.run(RpcUtil.java:79)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.com.google.protobuf.RpcUtil$1.run(RpcUtil.java:70)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:380)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:91)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:409)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:405)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.BufferCallBeforeInitHandler.userEventTriggered(BufferCallBeforeInitHandler.java:92)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:344)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:330)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:322)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.DefaultChannelPipeline$HeadContext.userEventTriggered(DefaultChannelPipeline.java:1428)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:344)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:330)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.DefaultChannelPipeline.fireUserEventTriggered(DefaultChannelPipeline.java:913)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcConnection.failInit(NettyRpcConnection.java:179)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcConnection.access$500(NettyRpcConnection.java:71)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcConnection$3.operationComplete(NettyRpcConnection.java:267)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcConnection$3.operationComplete(NettyRpcConnection.java:261)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>Caused by: java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:177)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:378)<br/>&nbsp; &nbsp;... 34 more<br/>Caused by: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>Caused by: java.net.ConnectException: Connection refused<br/>&nbsp; &nbsp;at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)<br/>&nbsp; &nbsp;at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.replication.TestReplicationEndpoint#testReplicationEndpointReturnsFalseOnReplicate	100	0	 0	0	4.87	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestSyncTimeRangeTracker#testSimpleInRange	201	0	 0	0	.05	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestSyncTimeRangeTracker#testRangeConstruction	201	0	 0	0	.05	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.regionserver.TestStripeStoreEngine#testCreateBasedOnConfig	100	0	 0	0	2.18	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.TestProcedureRecovery#testNoopLoad	100	0	 0	0	1.47	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.TestProcedureExecutor#testWorkerStuck	100	0	 0	0	1.91	
<img src="/images/failed.png" height="14" width="14">	org.apache.hadoop.hbase.client.TestSeparateClientZKCluster#testAsyncTable	39	0	 33	0	2.16	org.apache.hadoop.hbase.TableExistsException: org.apache.hadoop.hbase.TableExistsException: testAsyncTable<br/> at org.apache.hadoop.hbase.master.procedure.CreateTableProcedure.prepareCreate(CreateTableProcedure.java:249)<br/> at org.apache.hadoop.hbase.master.procedure.CreateTableProcedure.executeFromState(CreateTableProcedure.java:86)<br/> at org.apache.hadoop.hbase.master.procedure.CreateTableProcedure.executeFromState(CreateTableProcedure.java:52)<br/> at org.apache.hadoop.hbase.procedure2.StateMachineProcedure.execute(StateMachineProcedure.java:194)<br/> at org.apache.hadoop.hbase.procedure2.Procedure.doExecute(Procedure.java:959)<br/> at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execProcedure(ProcedureExecutor.java:1664)<br/> at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.executeProcedure(ProcedureExecutor.java:1411)<br/> at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.access$1100(ProcedureExecutor.java:78)<br/> at org.apache.hadoop.hbase.procedure2.ProcedureExecutor$WorkerThread.run(ProcedureExecutor.java:1980)<br/><br/><br/>java.util.concurrent.ExecutionException: <br/>org.apache.hadoop.hbase.TableExistsException: org.apache.hadoop.hbase.TableExistsException: testAsyncTable<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.master.procedure.CreateTableProcedure.prepareCreate(CreateTableProcedure.java:249)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.master.procedure.CreateTableProcedure.executeFromState(CreateTableProcedure.java:86)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.master.procedure.CreateTableProcedure.executeFromState(CreateTableProcedure.java:52)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.procedure2.StateMachineProcedure.execute(StateMachineProcedure.java:194)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.procedure2.Procedure.doExecute(Procedure.java:959)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execProcedure(ProcedureExecutor.java:1664)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.executeProcedure(ProcedureExecutor.java:1411)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.access$1100(ProcedureExecutor.java:78)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.procedure2.ProcedureExecutor$WorkerThread.run(ProcedureExecutor.java:1980)<br/><br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.TestSeparateClientZKCluster.testAsyncTable(TestSeparateClientZKCluster.java:242)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>&nbsp; &nbsp;at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)<br/>&nbsp; &nbsp;at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)<br/>&nbsp; &nbsp;at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>Caused by: org.apache.hadoop.hbase.TableExistsException: org.apache.hadoop.hbase.TableExistsException: testAsyncTable<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.master.procedure.CreateTableProcedure.prepareCreate(CreateTableProcedure.java:249)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.master.procedure.CreateTableProcedure.executeFromState(CreateTableProcedure.java:86)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.master.procedure.CreateTableProcedure.executeFromState(CreateTableProcedure.java:52)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.procedure2.StateMachineProcedure.execute(StateMachineProcedure.java:194)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.procedure2.Procedure.doExecute(Procedure.java:959)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execProcedure(ProcedureExecutor.java:1664)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.executeProcedure(ProcedureExecutor.java:1411)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.access$1100(ProcedureExecutor.java:78)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.procedure2.ProcedureExecutor$WorkerThread.run(ProcedureExecutor.java:1980)<br/><br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)<br/>&nbsp; &nbsp;at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.RemoteWithExtrasException.instantiateException(RemoteWithExtrasException.java:99)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.RemoteWithExtrasException.unwrapRemoteException(RemoteWithExtrasException.java:89)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.ConnectionUtils.translateException(ConnectionUtils.java:228)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRpcRetryingCaller.onError(AsyncRpcRetryingCaller.java:159)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncMasterRequestRpcRetryingCaller.lambda$doCall$4(AsyncMasterRequestRpcRetryingCaller.java:73)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.RawAsyncHBaseAdmin$1.run(RawAsyncHBaseAdmin.java:409)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.com.google.protobuf.RpcUtil$1.run(RpcUtil.java:79)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.com.google.protobuf.RpcUtil$1.run(RpcUtil.java:70)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:380)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:91)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:409)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:405)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcDuplexHandler.readResponse(NettyRpcDuplexHandler.java:162)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcDuplexHandler.channelRead(NettyRpcDuplexHandler.java:192)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:316)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)<br/>&nbsp; &nbsp;... 1 more<br/>Caused by: org.apache.hadoop.hbase.ipc.RemoteWithExtrasException(org.apache.hadoop.hbase.TableExistsException): org.apache.hadoop.hbase.TableExistsException: testAsyncTable<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.master.procedure.CreateTableProcedure.prepareCreate(CreateTableProcedure.java:249)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.master.procedure.CreateTableProcedure.executeFromState(CreateTableProcedure.java:86)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.master.procedure.CreateTableProcedure.executeFromState(CreateTableProcedure.java:52)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.procedure2.StateMachineProcedure.execute(StateMachineProcedure.java:194)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.procedure2.Procedure.doExecute(Procedure.java:959)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execProcedure(ProcedureExecutor.java:1664)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.executeProcedure(ProcedureExecutor.java:1411)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.access$1100(ProcedureExecutor.java:78)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.procedure2.ProcedureExecutor$WorkerThread.run(ProcedureExecutor.java:1980)<br/><br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:375)<br/>&nbsp; &nbsp;... 32 more<br/>
<img src="/images/failed.png" height="14" width="14">	org.apache.hadoop.hbase.client.TestSeparateClientZKCluster#	0	0	 48	0	196.76	Appears to be stuck in thread NIOServerCxn.Factory:0.0.0.0/0.0.0.0:59654<br/><br/>java.lang.Exception: Appears to be stuck in thread NIOServerCxn.Factory:0.0.0.0/0.0.0.0:59654<br/>&nbsp; &nbsp;at java.base@11.0.6/sun.nio.ch.EPoll.wait(Native Method)<br/>&nbsp; &nbsp;at java.base@11.0.6/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:120)<br/>&nbsp; &nbsp;at java.base@11.0.6/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124)<br/>&nbsp; &nbsp;at java.base@11.0.6/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:136)<br/>&nbsp; &nbsp;at app//org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:203)<br/>&nbsp; &nbsp;at java.base@11.0.6/java.lang.Thread.run(Thread.java:834)<br/>
<img src="/images/failed.png" height="14" width="14">	org.apache.hadoop.hbase.replication.TestReplicationEndpoint#testWALEntryFilterFromReplicationEndpoint	98	0	 2	0	8.00	Failed after attempts=15, exceptions:<br/>2020-02-03T21:48:46.631Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:46.738Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:46.948Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:47.257Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:47.768Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:48.780Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:50.800Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:54.812Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:49:04.910Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:49:16.545Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:49:26.583Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:49:36.663Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:49:56.720Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:16.780Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:36.921Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/><br/><br/>org.apache.hadoop.hbase.client.RetriesExhaustedException: <br/>Failed after attempts=15, exceptions:<br/>2020-02-03T21:48:46.631Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:46.738Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:46.948Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:47.257Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:47.768Z, org.apache.hadoop.hbase.ipc.FailedServerException: Call to coremetal16/10.44.13.71:51383 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:48.780Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:50.800Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:48:54.812Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:49:04.910Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:49:16.545Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:49:26.583Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:49:36.663Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:49:56.720Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:16.780Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>2020-02-03T21:50:36.921Z, java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/><br/>&nbsp; &nbsp;at java.base/java.lang.Thread.getStackTrace(Thread.java:1606)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.setStackTrace(FutureUtils.java:130)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.rethrow(FutureUtils.java:145)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.get(FutureUtils.java:168)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AdminOverAsyncAdmin.rollWALWriter(AdminOverAsyncAdmin.java:574)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.replication.TestReplicationEndpoint.setup(TestReplicationEndpoint.java:106)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>&nbsp; &nbsp;at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)<br/>&nbsp; &nbsp;at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>&nbsp; &nbsp;at --------Future.get--------(Unknown Source)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRpcRetryingCaller.completeExceptionally(AsyncRpcRetryingCaller.java:111)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncRpcRetryingCaller.onError(AsyncRpcRetryingCaller.java:181)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.AsyncAdminRequestRetryingCaller.lambda$doCall$4(AsyncAdminRequestRetryingCaller.java:68)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.client.RawAsyncHBaseAdmin$2.run(RawAsyncHBaseAdmin.java:431)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.com.google.protobuf.RpcUtil$1.run(RpcUtil.java:79)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.com.google.protobuf.RpcUtil$1.run(RpcUtil.java:70)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:380)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:91)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:409)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:405)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.BufferCallBeforeInitHandler.userEventTriggered(BufferCallBeforeInitHandler.java:92)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:344)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:330)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:322)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.DefaultChannelPipeline$HeadContext.userEventTriggered(DefaultChannelPipeline.java:1428)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:344)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:330)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.DefaultChannelPipeline.fireUserEventTriggered(DefaultChannelPipeline.java:913)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcConnection.failInit(NettyRpcConnection.java:179)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcConnection.access$500(NettyRpcConnection.java:71)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcConnection$3.operationComplete(NettyRpcConnection.java:267)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.NettyRpcConnection$3.operationComplete(NettyRpcConnection.java:261)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>Caused by: java.net.ConnectException: Call to coremetal16/10.44.13.71:51383 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:177)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:378)<br/>&nbsp; &nbsp;... 34 more<br/>Caused by: org.apache.hbase.thirdparty.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: coremetal16/10.44.13.71:51383<br/>Caused by: java.net.ConnectException: Connection refused<br/>&nbsp; &nbsp;at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)<br/>&nbsp; &nbsp;at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)<br/>&nbsp; &nbsp;at org.apache.hbase.thirdparty.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.TestProcedureMetrics#testMetricForSimpleProcedure	100	0	 0	0	.31	
<img src="/images/failed.png" height="14" width="14">	org.apache.hadoop.hbase.regionserver.TestRegionReplicasWithRestartScenarios#testWhenRestart	99	1	 0	0	11.12	expected:<61> but was:<59><br/><br/>java.lang.AssertionError: expected:<61> but was:<59><br/>&nbsp; &nbsp;at org.junit.Assert.fail(Assert.java:89)<br/>&nbsp; &nbsp;at org.junit.Assert.failNotEquals(Assert.java:835)<br/>&nbsp; &nbsp;at org.junit.Assert.assertEquals(Assert.java:647)<br/>&nbsp; &nbsp;at org.junit.Assert.assertEquals(Assert.java:633)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.regionserver.TestRegionReplicasWithRestartScenarios.assertReplicaDistributed(TestRegionReplicasWithRestartScenarios.java:159)<br/>&nbsp; &nbsp;at org.apache.hadoop.hbase.regionserver.TestRegionReplicasWithRestartScenarios.testWhenRestart(TestRegionReplicasWithRestartScenarios.java:140)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>&nbsp; &nbsp;at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>&nbsp; &nbsp;at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)<br/>&nbsp; &nbsp;at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)<br/>&nbsp; &nbsp;at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)<br/>&nbsp; &nbsp;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)<br/>&nbsp; &nbsp;at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)<br/>&nbsp; &nbsp;at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)<br/>&nbsp; &nbsp;at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>&nbsp; &nbsp;at java.base/java.lang.Thread.run(Thread.java:834)<br/>
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.TestProcedureEvents#testTimeoutEventProcedureDoubleExecutionKillIfSuspended	100	0	 0	0	8.28	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.TestProcedureRecovery#testStateMachineMultipleLevel	100	0	 0	0	.30	
<img src="/images/passed.png" height="17" width="17">	org.apache.hadoop.hbase.procedure2.TestProcedureExecutor#testSubmitBatch	100	0	 0	0	1.13	
